local_resinos:
  app-name: container-lifecycle
  build-triggers:
    - Dockerfile: d25e2278ae0d36537205b8586424e4d5a5538adfe6e1aeec7395af242e6b02f7
  environment:
    - RESIN_vars=There Are None for resinOS Unmanaged
destination: /usr/src/app
ignore:
  - .git
  - Dockerfile
